Enable pulling of translations in specific branch

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,9 +11,6 @@ on:
   schedule:
     - cron: '0 14 * * 5'
 
-permissions:
-  contents: read
-
 env:
   TX_CLI_VERSION: '1.6.7'
   PYTHON_NEWEST: '3.12'      # Latest Python version being translated
@@ -28,17 +25,19 @@ jobs:
       - uses: actions/checkout@v3
       - id: version
         run: echo "matrix=$(cat .github/versions.txt)" >> $GITHUB_OUTPUT
-  
+
   update:
     runs-on: ubuntu-latest
     needs: trigger
+    permissions:
+      contents: write
     strategy:
       max-parallel: 1
       fail-fast: false
       matrix:
         cpython_version: ${{fromJson(needs.trigger.outputs.matrix)}}
         # must match existent projects in Transifex
-    
+
     steps:
       - name: Check out ${{ github.repository }}
         uses: actions/checkout@v3
@@ -51,10 +50,20 @@ jobs:
           ref: ${{ matrix.cpython_version }}
           path: cpython
 
-      - name: Set up Python 3.9
+      - name: Create branch ${{ matrix.cpython_version }} if missing
+        run: |
+          bash scripts/create-missing-branch.sh ${{ matrix.cpython_version }}
+
+      - name: Check out ${{ github.repository }}
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ matrix.cpython_version }}
+          path: cpython/Doc/locales
+
+      - name: Set up Python 3
         uses: actions/setup-python@v4
         with:
-          python-version: '3.9'
+          python-version: '3'
           cache: 'pip'
           cache-dependency-path: |
             "requirements/*.txt'
@@ -77,6 +86,7 @@ jobs:
         run: |
           ver=$(echo ${{ matrix.cpython_version }} | sed 's|\.||')
           echo "TX_PROJECT=python-$ver" >> $GITHUB_ENV
+          echo ${{ env.TX_PROJECT }}
 
         # required for generating .tx/config
       - name: Generate POT files
@@ -89,6 +99,7 @@ jobs:
         run: |
           sphinx-intl create-txconfig
           sphinx-intl update-txconfig-resources --pot-dir pot --locale-dir . --transifex-organization-name python-doc --transifex-project-name ${{ env.TX_PROJECT }}
+          sed -i '/^minimum_perc = 0$/s/0/1/' .tx/config
 
       - name: Push source strings to Transifex
         if: ${{ !contains(fromJSON('["push", "pull_request"]'), github.event_name) ||
@@ -104,3 +115,25 @@ jobs:
           python3 scripts/lock-translations.py cpython/Doc/locales/.tx/config ${{ env.TX_PROJECT }}
         env:
           TX_TOKEN: ${{ secrets.TX_TOKEN }}
+
+      - name: Pull translations for all languages
+        working-directory: cpython/Doc/locales
+        id: tx_pull
+        run: |
+          tx pull --all --translations --force
+        env:
+          TX_TOKEN: ${{ secrets.TX_TOKEN }}
+
+      # tx pull takes some time and have big chances of connection error,
+      # so make to to commit downloaded PO successfully downloads on
+      # failure or success.
+      - name: Commit and push changes
+        working-directory: cpython/Doc/locales
+        if: contains(fromJSON('["failure", "success"]'), steps.tx_pull.outcome)
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git status
+          git diff -I'^"POT-Creation-Date: ' --numstat *.po **/*.po **/*.pot | cut -f3 | xargs -r git add
+          git add $(git ls-files -o --exclude-standard *.po **/*.po **/*.pot) .tx/config
+          git diff-index --cached --quiet HEAD || { git commit -m "Update translations from ${{ env.BRANCH }}" && git push; }
